tasks:
  - before: cd docs
    init: gp sync-await install && yarn install
    command: yarn start
  - init: yarn install && gp sync-done install
    command: yarn run dev

ports:
  - port: 8000
    onOpen: open-preview
  - port: 5000
    onOpen: open-preview
